### ISSUE TITLE
abandoned

### ISSUE THREAD

**Issue by bvarent** [phly/PhlyRestfully#130]
This project seems to be canabalized by Apigility. Which is a great project. But it would be nice to have some kind of note of that somewhere. To prevent people (like me) reading up on and starting with PhlyRestfully, before finding out Apigility is the successor.

**Comment by weierophinney** [comment]
I'll update the project soon with information to this effect. Essentially, I created PhlyRestfully, and its success validated a direction we decided on within the ZF team that APIs deserved a dedicated project. Apigility separates the discrete behaviors into their own modules, allowing the ability to compose the behaviors your want in your application, or opt-in to a REST engine with full capabilities. It also adds a number of behaviors I never got to in PhlyRestfully, such as validation, authentication, and authorization. For those reasons, I recommend the modules in zfcampus over PhlyRestfully at this point.

What I would like to do is write a migration guide for those using PhlyRestfully, so they can migrate to Apigility. For that reason, I'll leave this issue open, to track that progress.
