### ISSUE TITLE
Possibility to hide _embedded  data

### ISSUE THREAD

**Issue by acabala** [phly/PhlyRestfully#6]
Sometimes it happens that because of using filter parameters in request  content of response changes.
For example we have path `/items` that, returns the whole collection of requested items, but sometimes there is need to use filter like `/items?countUnseen=true`, that supposes to return number of unseen items.
Currently it works like:

```
{
    "countUnseen":"0",
    "_links":{
        "self":{
          "href":"items/?countUnseen=true"
            }
        },
    "_embedded":{
        "items":[
        ]
    }
}
```

in that kind of response `_embedded` object is not necessarily at all, but it makes response more messy, as well as consumes little more bandwidth.
It would be good to have possibility to disable `_embedded` in response if developer wants it.

**Comment by jkobus** [comment]
`_embedded` property is optional: [draft-kelly-json-hal-06 section-4.1.2](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-4.1.2); moreover embedded resources should also be represented by a link in the `_links` section as stated in [draft-kelly-json-hal-06 section-8.3](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-8.3).

Example provided above may look more like:

```
{
    ...
    "_links": {
        "self": {
            "href": "items/?unseen=true"
        },
        "items": []
    }
}
```

RFC is inconsistent as the example in [section-6](https://tools.ietf.org/html/draft-kelly-json-hal-08#section-6) does not meet  this requirments (mikekelly/hal_specification#16).
